### ISSUE TITLE
Papart Project, need to create markers and get the rotation

### ISSUE THREAD

**Issue by enric1994** [natar-io/PapARt#1]
Hi,
I am a telecommunications student from Barcelona and I want to start a project using Processing (I use it since 2013) and augmented reality.
 I have some questions about the functionalities of Papart:
-How to generate a single marker (the .svg and the .cvg (and a cube marker if possible)).
-How to get the rotation of the marker ( like .getLocationVector()).

With that two features I am ready to start my project.

Thanks!

Enric Moreu

**Comment by poqudrof** [comment]
Hello Enric !

It was indeed missing from the [wiki](https://github.com/poqudrof/Papart-examples/wiki), there was a page explaining it but I can't find it right now. So I made a [create your markerboard](https://github.com/poqudrof/Papart-examples/wiki/markerboard) page.  

You can get the location of the PaperScreen with the `getLocation()` method: 

http://jiii.fr/papart/papart/javadoc/fr/inria/papart/procam/PaperScreen.html

Cheers, 
Jeremy.

**Comment by enric1994** [comment]
Thanks! 
The tutorial of the markerboards is very useful but I don't found any function to get the rotation in the javadoc :(

**Comment by poqudrof** [comment]
What do you want as "rotation" ? 

The method I pointed gives you the rotation matrix. If you are new to 3D transformations try to find explanations online such as this:
http://mathworld.wolfram.com/RotationMatrix.html 
http://www.cs.umd.edu/~djacobs/CMSC427/Transformations2.pdf

**Comment by enric1994** [comment]
Thank you, very useful info. My project goes well! In the next weeks I am going to update it.
More questions:
-How to detect when the marker is not in the screen?
-Any suggestion about the webcam? I use Linux and I need to buy one.
-In the "create your markerboard" i don't find how to generate the .cfg file. It is only necessary for multimarker codes?

Cheers!

**Comment by poqudrof** [comment]
Markers are not distinct in PapARt. You can get the MarkerBoard location in different ways. 
 
In your PaperScreen use the `getBoard` method, then on the markerBoard object. Here are some methods you can try: 

``` java
 // (in the x extends PaperSreen code)

MarkerBoard board = getBoard(); 
Camera camera = getCameraTracking(); 
ARDisplay display = getDisplay();

// In display space
float distance = board.lastMovementDistance(camera); 
PVector screenLocation = board.getBoardLocation(camera, display);

// In 3D Space
PMatrix3D boardLocation = getLocation();
PVector locationVector = getLocationVector();
```

I recommend the PlayStationEye webcam, it is super cheap (you can get them < 10$) and the quality is great for AR. If you have stronger requirements you can try [Logitech](http://www.logitech.com/en-us/video/webcams) webcams like the C525 or C920. They have better resolution, but the PSEye is a gem for augmented reality. 

---

You need to make CFG files **only** for tracking markers on different 3D orientations only (like the cube). If you track planar objects use the SVG guide.
