### ISSUE TITLE
CamerFactory.createCamera does not support REALSENSE enumerated type

### ISSUE THREAD

**Issue by aaronblishen** [natar-io/PapARt#10]
java.lang.RuntimeException: ProCam, Camera: Unspported camera Type
	at fr.inria.papart.procam.camera.CameraFactory.createCamera(CameraFactory.java:84)

When using REALSENSE.  I can submit a pull request for you if you want..

**Comment by poqudrof** [comment]
Hello, 
That is quite strange indeed that the REALSENSE driver is not included in the  1.1  release. 
I look into it. 

-- I found the issue -- it is reverted back 

I will post a release 1.1.1  this week, or the next one once everything is tested. 
With this new version, there will be a tutorial on how to create markerboards with ARToolkit markers of the forum. 
You can ask questions about anything I will be glad to answer:  http://forum.rea.lity.tech . 
Cheers, 
Jeremy.
