### ISSUE TITLE
cant build - https required?

### ISSUE THREAD

**Issue by trackme518** [natar-io/PapARt#12]
Hi, I am trying to build the library on win64 with latest maven and java JDK (apache-maven-3.6.3 +jdk-13.0.2 ):

[ERROR] Failed to execute goal on project papart: Could not resolve dependencies for project fr.inria:papart:jar:1.1: Failed to collect dependencies at com.mkobos:pca_transform:jar:1.0.2: Failed to read artifact descriptor for com.mkobos:pca_transform:jar:1.0.2: Could not transfer artifact com.mkobos:pca_transform:pom:1.0.2 from/to central (http://repo1.maven.org/maven2): Transfer failed for http://repo1.maven.org/maven2/com/mkobos/pca_transform/1.0.2/pca_transform-1.0.2.pom 501 HTTPS Required -> [Help 1]

**Comment by Dimlight** [comment]
Hi, I am facing the same problem. Also the forum's link is not working. Can you please provide any tutorial to run the examples and regarding installation process. It will help if I am missing something.

**Comment by poqudrof** [comment]
Hello, the project is currently without support.

I will try to revive it in the next weeks, first to make it work with the libraries of 2018, maybe work an update for more recent versions of Processing and JavaCV.

**Comment by erorabaugh** [comment]
> Hello, the project is currently without support.
> 
> I will try to revive it in the next weeks, first to make it work with the libraries of 2018, maybe work an update for more recent versions of Processing and JavaCV.

Yes please!!
