### ISSUE TITLE
Use my classes with PaperScreen

### ISSUE THREAD

**Issue by enric1994** [natar-io/PapARt#2]
Hi :blush: ,
I would like to use my previous [3D animation sketches](https://github.com/enric1994/CUBE) with PapARt. 
For example, i want to display my class MyBox with augmented reality:
`public class Block {`
 int size;
  Block(int _size) {
    size=_size;
  }
  void display() {
  box(size, size, size);
  }
}

What I have to do to use correctly this class in the sketch "planetes" (display the box instead of the earth)?
I am having some issues importing audios too, they can only be declared in the main class?

Tanks in advance,

Enric

**Comment by poqudrof** [comment]
It might be OK if you use your `Block` class as an internal class of a PaperScreen... another possibility is to rewrite like this:  

``` java
public class Block {
  int size;
  Block(int _size) { 
   size=_size; 
 }
   void display(PGraphics g) {
     g.box(size, size, size);
    }
}
```

You can get your `PGraphics` object by calling the `getGraphics()` method in a PaperScreen.
