### ISSUE TITLE
colorDetection.getImage() returns slanted result

### ISSUE THREAD

**Issue by vcz-fr** [natar-io/PapARt#5]
Hello,

This is what I'm getting when trying to get the feed from the camera for processing purposes:

![image](https://cloud.githubusercontent.com/assets/9070606/21993752/c3085e90-dc1c-11e6-9d9a-7fe0eed11111.png)

I'm currently using PapARt on a separate applet that I launch separately on startup. The image seems slanted.
Here's the piece of code I use to extract the camera stream from the PapARt applet:
```
void drawOnPaper() {
    clear();
    webcamSnapshot = colorDetection.getImage(); // Extracts frame here
    colorDetection.drawCaptureZone();
}
```

**Comment by poqudrof** [comment]
Hello, 
I'm sorry to say it is a known issue. The problem comes from underneath PapARt: either JavaCV, or OpenCV. 
A fix is to use always even numbers at least.  Indeed it should be notified in the javadoc of TrackedView and ColorDetection in setImageWidthPx and setImageHeightPx.
