### ISSUE TITLE
Errors while compiling Papart 

### ISSUE THREAD

**Issue by masterchef8** [natar-io/PapARt#9]
Hello,

FYI : I have those following warnings and errors while trying to compile this repo. 

> [WARNING] The POM for org.processing:core:jar:3.2.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
>[WARNING] The POM for tech.lity.rea:SVGExtended:jar:3.3.4 is missing, no dependency information available
>[WARNING] The POM for org.processing:core:jar:3.0b4 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

>[ERROR] Failed to execute goal on project papart: Could not resolve dependencies for project fr.inria:papart:jar:1.0: Failure to find tech.lity.rea:SVGExtended:jar:3.3.4 in http://clojars.org/repo was cached in the local repository, resolution will not be reattempted until the update interval of clojars.org has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read ...

**Comment by poqudrof** [comment]
You need to compile SVGExtended, as explained in the wiki page:  https://github.com/poqudrof/PapARt/wiki/Compilation

I updated the pom to get the SVGExtended distributed by realityTech.
